# docker-compose.e2e.yml — overlay that waits on TCP so HTTP/HTTPS doesn't matter
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
      args:
        BUILD_VERSION: ${APP_VERSION:-dev}
        BUILD_COMMIT: ${GIT_COMMIT:-dev}
        BUILD_DATE: ${BUILD_DATE:-unknown}
        VCS_URL: ${VCS_URL:-https://example.com/repo}
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-local}/${APP_NAME:-mrv}-e2e:${APP_VERSION:-dev}
    container_name: mrv-e2e
    depends_on:
      - web
    working_dir: /e2e
    environment:
      # Default to HTTP unless you explicitly enable SSL in the web service
      - CYPRESS_baseUrl=http://web:4200
      # If you enabled SSL on ng serve, uncomment the two below:
      # - CYPRESS_baseUrl=https://web:4200
      # - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./:/e2e
    # Wait for the port to open (works for both HTTP and HTTPS), then run Cypress
    entrypoint: [ "bash", "-lc", "npm ci || npm install; npx --yes wait-on tcp:web:4200 --timeout 600000 && npx cypress run" ]
