# docker-compose.e2e.yml — overlay (updated) waits for the web server before running Cypress
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
      args:
        BUILD_VERSION: ${APP_VERSION:-dev}
        BUILD_COMMIT: ${GIT_COMMIT:-dev}
        BUILD_DATE: ${BUILD_DATE:-unknown}
        VCS_URL: ${VCS_URL:-https://example.com/repo}
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-local}/${APP_NAME:-mrv}-e2e:${APP_VERSION:-dev}
    container_name: mrv-e2e
    depends_on:
      - web
    working_dir: /e2e
    environment:
      # If you enabled SSL for ng serve, switch to https and set NODE_TLS_REJECT_UNAUTHORIZED=0
      # CYPRESS_baseUrl=http://web:4200
      - CYPRESS_baseUrl=https://web:4200
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./:/e2e
    # Wait for the dev server to be reachable, then run Cypress
    entrypoint: [ "bash", "-lc", "npm ci || npm install; npx --yes wait-on https-get://web:4200 --timeout 300000 && npx cypress run" ]
