services:
  web:
    image: node:22-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: >
      sh -c "npm ci &&
             npm run doctor &&
             npx ng serve --host 0.0.0.0 --port 4200
                          --proxy-config proxy.conf.docker.json
                          --poll=2000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '4200:4200'
    depends_on:
      mock-api:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "http=require('http');http.get('http://127.0.0.1:4200',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))",
        ]
      interval: 10s
      timeout: 3s
      retries: 10

  mock-api:
    image: node:22-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: >
      sh -c "npm ci && node mock-api/server.cjs"
    ports:
      - '3001:3001'
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "http=require('http');http.get('http://127.0.0.1:3001/kpis',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
