# docker-compose.e2e.yml — overlay that replaces the e2e service to use Node 22
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    container_name: mrv-e2e
    depends_on:
      - web
    working_dir: /e2e
    environment:
      # If you enabled SSL for ng serve, switch to https and set NODE_TLS_REJECT_UNAUTHORIZED=0
      # CYPRESS_baseUrl=http://web:4200
      - CYPRESS_baseUrl=https://web:4200
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./:/e2e
    entrypoint: [ "bash", "-lc", "npm ci || npm install; npx cypress run" ]
