services:
  traefik:
    image: traefik:v3.4
    container_name: mrv-traefik
    command:
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.websecure.address=:4443     # inside container
      - --api.dashboard=true
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "4443:4443"                               # host:container
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro
    depends_on:
      - web
      - api
    profiles: ["traefik"]

  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`) || Host(`127.0.0.1`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=4200"
      - "traefik.http.routers.web.priority=1"

  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=(Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip"
      - "traefik.http.routers.api.priority=100"
