name: Bug report
description: File a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce }
  - type: textarea
    id: expected
    attributes: { label: Expected behavior }
  - type: input
    id: version
    attributes: { label: Version/commit }
