name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --passWithNoTests --coverage
      - run: npx ng build --configuration=production
      # Uncomment to enable Cypress in CI (requires baseUrl or services)
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     install: false
      #     start: npm start
      #     wait-on: 'http://localhost:4200'
