name: Docker
on:
  push:
    tags: ['v*.*.*']
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: v
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mrv-web:${{ steps.v.outputs.TAG }}
            ghcr.io/${{ github.repository }}/mrv-web:latest
